create database CSE_B2_423

USE CSE_B2_423

CREATE TABLE DEPOSITE(
ACTNO INT,
CNAME VARCHAR(50),
BNAME VARCHAR(50),
AMOUNT DECIMAL(8,2),
ADATE DATETIME
)

INSERT INTO  DEPOSITE VALUES (101 ,'ANIL' ,'VRCE' ,1000.00 ,'01-MAR-1995'),
                             (102 ,'SUNIL' ,'AJNI' ,5000.00 ,'04-JAN-1996'),
                             (103 ,'MUHUL' ,'KAROLBAGH' ,3500.00 ,'17-NOV-1995'),
							 (104 ,'MADHURI' ,'CHANDI' ,1200.00 ,'17-DEC-1995'),
							 (105 ,'PRAMOD' ,'M.G.ROAD' ,3000.00 ,'27-MAR-1996'),
							 (106 ,'SANDIP' ,'ANDHERI' ,2000.00 ,'31-MAR-1996'),
							 (107 ,'SIVANI' ,'VIRAR' ,1000.00 ,'05-OCT-1995'),
							 (108 ,'KRANTI' ,'NEHRU PLACE ',5000.00 ,'02-JUL-1995'),
							 (109 ,'MINU' ,'POWAI' ,7000.00 ,'10-SEP-1995')

CREATE TABLE BRANCH(
-BNAME VARCHAR(50),
CITY VARCHAR(50)
);

INSERT INTO BRANCH VALUES  
('VRCE' ,'NAGPUR'),
('AJNI' ,'NAGPUR'),
('KAROLBAGH' ,'DELHI'),
('CHANDI' ,'DELHI'),
('DHARAMPETH' ,'NAGPUR'),
('M.G. ROAD','BANGLORE'),
('ANDHERI' ,'BOMBAY'),
('VIRAR ','BOMBAY'),
('NEHRU' ,'PLACE DELHI'),
('POWAI' ,'BOMBAY')


CREATE TABLE CUSTOMERS(
CNAME VARCHAR(50),
CITY VARCHAR(50)
)

INSERT INTO CUSTOMERS VALUES  
('ANIL' ,'CALCUTTA'),
('SUNIL' ,'DILHI'),
('MEHUL' ,'BARODA'),
('MANDAR' ,'PATNA'),
('MADHURI' ,'NAGPUR'),
('PRAMOD','NAGPUR'),
('SANDIP' ,'SURAT'),
('SHIVANI ','BOMBAY'),
('KRANTI' ,'BOMBAY'),
('NAREN' ,'BOMBAY')

CREATE TABLE BORROW(
LOANNO INT,
CNAME VARCHAR(50),
BNAME VARCHAR(50),
AMOUNT DECIMAL(8,2)
);


INSERT INTO  BORROW VALUES

(201 ,'ANIL' ,'VRCE' ,1000.00 ),
 (206 ,'MUHUL' ,'AJNI' ,5000.00 ),
  (311 , 'SUNIL','DHARAMPETH' ,3000.00 ),
   (321 ,'MADHURI' ,'ANDHERI' ,2000.00 ),
	(375 ,'PRAMOD' ,'VIRAR' ,8000.00 ),
     (481 ,'KRANTI' ,'NEHRU PLACE' ,3000.00 )
	 


-- QUERIES LAB_2_PART_A

SELECT * FROM DEPOSITE
SELECT * FROM BORROW
SELECT * FROM CUSTOMERS
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSITE
SELECT LOANNO,AMOUNT FROM BORROW
SELECT * FROM BORROW WHERE BNAME='ANDHERI'
SELECT ACTNO,AMOUNT FROM DEPOSITE WHERE ACTNO=106
SELECT CNAME FROM BORROW WHERE AMOUNT>5000
SELECT CNAME FROM DEPOSITE WHERE ADATE>'01-DEC-1996'
SELECT CNAME FROM DEPOSITE WHERE ACTNO<105
SELECT CNAME FROM CUSTOMERS WHERE  CITY IN ('NAGPUR','DELHI')
SELECT CNAME,BNAME FROM DEPOSITE WHERE AMOUNT >4000 AND ACTNO<105
SELECT * FROM BORROW WHERE AMOUNT>=3000 AND AMOUNT<=8000
SELECT * FROM BORROW WHERE AMOUNT BETWEEN 3000 AND 8000 -- SAME QUERIES AS ABOVE
SELECT * FROM DEPOSITE WHERE BNAME <> 'ANDHERI'
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSITE WHERE BNAME IN ('AJNI','KAROLBAGH','M.G. ROAD ') AND ACTNO<104



-- QUERIES LAB_2_PART_B

SELECT TOP 5 * FROM DEPOSITE
SELECT TOP 3 * FROM DEPOSITE WHERE AMOUNT>1000
SELECT TOP 5 LOANNO,CNAME FROM BORROW WHERE BNAME <> 'ANDHERI'
SELECT DISTINCT CITY FROM CUSTOMERS 
SELECT DISTINCT BNAME FROM BRANCH


-- QUERIES LAB_2_PART_C

SELECT TOP 50 PERCENT * FROM BORROW
SELECT TOP 10 PERCENT AMOUNT FROM DEPOSITE
SELECT TOP 25 PERCENT * FROM DEPOSITE WHERE AMOUNT>5000
SELECT TOP 10 PERCENT AMOUNT FROM BORROW
SELECT DISTINCT CNAME,CITY FROM CUSTOMERS
SELECT *, AMOUNT + (AMOUNT * 0.1)AS INCREMENTCOLUME FROM BORROW
SELECT LOANNO FROM BORROW WHERE  (LOANNO%2=0) -- FOR EVEN
SELECT LOANNO FROM BORROW WHERE  (LOANNO%2<>0) -- FOR ODD




------ LAB_3------

--PART_A

CREATE TABLE CRICKET(
PNAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT
);

INSERT INTO CRICKET VALUES
('Sachin Tendulkar', 'Mumbai' ,30),
('Rahul Dravid ','Bombay' ,35),
('M. S. Dhoni ','Jharkhand' ,31),
('Suresh Raina' ,'Gujarat', 30)


SELECT * INTO WORLDCUP FROM CRICKET 
SELECT PNAME,CITY INTO T20 FROM CRICKET WHERE 1=0
SELECT * INTO IPL FROM CRICKET WHERE 1=0






--PART_B

CREATE TABLE EMPLOYEE
(
ENAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT
);

INSERT INTO EMPLOYEE VALUES
('Jay Patel', 'Rajkot ' ,30),
('Rahul Dave ','Baroda ' ,35),
('Jeet Pate ','Surat' ,31),
('Vijay Raval ' ,'Rajkot ', 30)


SELECT * INTO EMPLOYEE_DETAIL FROM EMPLOYEE
SELECT ENAME,CITY INTO EMPLOYEE_DATA FROM EMPLOYEE WHERE 1=0
SELECT * INTO EMPLOYEE_INFO FROM EMPLOYEE WHERE 1=0

--PART_C

INSERT INTO EMPLOYEE_INFO SELECT * FROM EMPLOYEE
WHERE CITY ='Rajkot'

INSERT INTO EMPLOYEE_INFO SELECT * FROM EMPLOYEE
WHERE AGE>32



------UPDATE-----

---PART_A
UPDATE DEPOSITE
SET AMOUNT=5000
WHERE AMOUNT=3000

UPDATE BORROW
SET BNAME=' C.G. ROAD'
WHERE BNAME='VRCE'

UPDATE DEPOSITE
SET ACTNO=111,AMOUNT=5000
WHERE CNAME='SANDIP'

UPDATE DEPOSITE
SET AMOUNT=7000
WHERE CNAME='KRANTI'

UPDATE BRANCH
SET CITY='ANDHERI WEST'
WHERE CITY='ANDHERI'


UPDATE DEPOSITE
SET BNAME='NAHRU PALACE'
WHERE CNAME='MEHUL'

UPDATE DEPOSITE
SET AMOUNT =5000
WHERE ACTNO BETWEEN 103 AND 107


UPDATE DEPOSITE
SET ADATE ='1995-04-01'
WHERE CNAME='ANIL'


UPDATE DEPOSITE
SET AMOUNT=10000
WHERE CNAME='MINU'


UPDATE DEPOSITE
SET AMOUNT=5000,ADATE ='1996-04-01'
WHERE CNAME='PRAMOD'



--PART_B


UPDATE BORROW
SET AMOUNT=(AMOUNT+AMOUNT*0.1)


UPDATE DEPOSITE
SET AMOUNT=(AMOUNT+AMOUNT*0.2)


--PART_C

UPDATE BORROW
SET AMOUNT=NULL
WHERE LOANNO=321

UPDATE BORROW
SET BNAME=NULL
WHERE CNAME='KRANTI'

SELECT BNAME FROM BORROW WHERE BNAME IS NULL

SELECT BNAME FROM BORROW WHERE BNAME <> NULL

--- INCOMPLATE--



-----LAB_4-----


--PART_A

 --1.Add two more columns City VARCHAR (20) and Pincode INT
ALTER TABLE DEPOSITE 
ADD CITY VARCHAR(20),PINCODE INT

 --2.Change the size of CNAME column from VARCHAR (50) to VARCHAR (35).
ALTER  TABLE DEPOSITE 
ALTER COLUMN CNAME VARCHAR(35)

 --3.Change the data type DECIMAL to INT in amount Column.
EXEC SP_RENAME 'DEPOSITE.ACTNO', 'ANO'

--4. Rename Column ActNo to ANO.
ALTER TABLE DEPOSITE 
ALTER COLUMN AMOUNT INT

--5. Delete Column City from the DEPOSIT table.
ALTER TABLE DEPOSITE 
DROP COLUMN CITY

--6. Change name of table DEPOSIT to DEPOSIT_DETAIL.
EXEC SP_RENAME 'DEPOSITE','DEPOSITE_DETAIL'

--PART_B

--1. Rename Column ADATE to AOPENDATE OF DEPOSIT_DETAIL table.
EXEC SP_RENAME 'DEPOSITE_DETAIL.ADATE', 'AOPENDATE'

--2. Delete Column AOPENDATE from the DEPOSIT_DETAIL table.
ALTER TABLE DEPOSITE_DETAIL 
DROP COLUMN AOPENDATE

--3. Rename Column CNAME to CustomerName.
EXEC SP_RENAME 'DEPOSITE_DETAIL.CNAME', 'CustomerName'


--PART_C
CREATE TABLE STUDENT_DETAIL(
ENROLLMENT_NO VARCHAR(20),
NAME VARCHAR(25),
CPI DECIMAL(5,2),
BIRTHDATE DATETIME
)

--1. Add two more columns City VARCHAR (20) (Not null) and Backlog INT (Null).
ALTER TABLE STUDENT_DETAIL 
ADD CITY VARCHAR(20) NOT NULL,BACKLOG INT NULL

--2. Change the size of NAME column of student_detail from VARCHAR (25) to VARCHAR (35).
ALTER  TABLE STUDENT_DETAIL 
ALTER COLUMN  NAME  VARCHAR(25)

--3. Change the data type DECIMAL to INT in CPI Column.
ALTER  TABLE STUDENT_DETAIL 
ALTER COLUMN  CPI  INT

--4. Rename Column Enrollment_No to ENO.
EXEC SP_RENAME 'STUDENT_DETAIL.ENROLLMENT_NO', 'ENO'

--5. Delete Column City from the student_detail table.
ALTER TABLE STUDENT_DETAIL 
DROP COLUMN CITY

--6. Change name of table student_detail to STUDENT_MASTER.
EXEC SP_RENAME 'STUDENT_DETAIL', 'STUDENT_MASTER'
